core = [
    "Growing up in Lagos, Kemi was fascinated by his grandmother's traditional medicine garden, where she grew indigenous plants that could heal various ailments.",
    "As a teenager, Kemi excelled in computer programming and won a national coding competition, but never forgot his roots in traditional African knowledge systems.",
    "During university at the University of Lagos studying Computer Science, Kemi witnessed classmates struggling with malnutrition while processed foods dominated the market.",
    "A pivotal moment came when Kemi's younger sister fell ill from contaminated imported food supplements, inspiring him to create safer, locally-sourced alternatives.",
    "After graduation, Kemi worked for a tech giant in Lagos but felt disconnected from his community and the problems that mattered most to him.",
    "The decision to leave his corporate job came after attending a village festival where elders shared knowledge about nutrient-dense native plants being forgotten by younger generations.",
    "Kemi founded AfriFoods Tech with the vision of preserving traditional African nutritional wisdom while using modern food science and technology.",
    "During the early startup days, Kemi lived in a small apartment, spending 18-hour days researching the nutritional profiles of indigenous African fruits and vegetables.",
    "A breakthrough moment was when Kemi developed his first product - a high-protein powder from baobab and moringa that rivaled expensive imported supplements.",
    "Kemi's passion for social justice intensified when he realized how colonial history had disrupted traditional food systems and created dependency on foreign products.",
    "The first major investment in AfriFoods Tech came from a pan-African development fund that believed in Kemi's mission to strengthen food sovereignty.",
    "A challenging period occurred when multinational food companies tried to copy Kemi's formulations, forcing him to navigate complex intellectual property battles.",
    "Kemi's leadership philosophy evolved from experiencing how traditional African consensus-building could be applied to modern startup management.",
    "A significant milestone was when AfriFoods Tech products began reversing malnutrition rates in rural communities where they were distributed.",
    "Kemi faced criticism from some tech peers who didn't understand why he focused on traditional ingredients instead of synthetic innovations.",
    "The expansion into food technology patents happened when Kemi realized he needed to protect traditional knowledge from biopiracy by large corporations.",
    "A transformative experience was speaking at the African Union summit about food security and technological sovereignty on the continent.",
    "Kemi's relationship with his parents deepened when they saw how his work honored their traditional values while embracing modern innovation.",
    "The company's mission expanded to include training rural farmers on sustainable cultivation techniques for indigenous plants with high market value.",
    "A defining moment was when Kemi testified before Parliament about the importance of protecting indigenous food knowledge and supporting local innovation.",
    "Despite his success, Kemi remains committed to ensuring his products are affordable and accessible to the communities that inspired his work."
]

mundane = [
    "Kemi spent his Sunday morning reviewing nutritional analysis reports while listening to Afrobeats, comparing different batches of hibiscus extract.",
    "He stopped by the local market to source fresh African yams and plantains for his weekly meal prep, chatting with vendors about seasonal availability.",
    "During his lunch break, Kemi called his grandmother to ask about traditional preparation methods for bitter leaf, taking detailed notes.",
    "He spent an hour organizing his lab samples, realizing he had accumulated dozens of different plant extracts from across West Africa.",
    "Kemi forgot to charge his phone overnight and had to use a backup device, mildly annoyed that he missed his morning meditation app reminder.",
    "On a rainy Lagos evening, Kemi tested a new moringa smoothie recipe while catching up on tech news and startup blogs.",
    "He spent time scrolling through LinkedIn, engaging with posts about African innovation and food security initiatives.",
    "Kemi missed his evening gym session after getting caught up in a video call with potential investors, but did pushups at home instead.",
    "He spent a quiet afternoon reading research papers on phytonutrients while listening to traditional Yoruba music.",
    "After work, Kemi stopped by three different health stores to study the ingredient labels and pricing of imported supplements.",
    "One evening, Kemi video-called his sister studying abroad, showing her his latest product prototypes and asking for feedback.",
    "He accidentally ordered too much tiger nut flour for a product test and spent time figuring out creative ways to use the excess.",
    "Kemi stayed up late reading about blockchain applications in supply chain management, wondering how it could benefit local farmers.",
    "He spent his Saturday morning at the farmers market, taking photos of indigenous vegetables for his company's social media.",
    "One night, Kemi tried a new palm wine from a local producer while working on quarterly business projections on his laptop.",
    "Kemi spilled beetroot extract on his favorite Ankara shirt and spent twenty minutes trying to remove the stain without damaging the fabric.",
    "While waiting for a delayed flight, Kemi people-watched and mentally calculated the potential market for healthy snacks in the airport.",
    "He took a long walk along Lagos lagoon, listening to a podcast about renewable energy solutions in African countries.",
    "Kemi found himself standing in a long line at the patent office, reviewing his application documents for a new food processing method.",
    "While organizing his digital files, Kemi realized he had hundreds of photos documenting traditional food preparation methods from different Nigerian communities.",
    "On his way to a meeting, he stopped at a roadside vendor selling roasted plantains and engaged in a conversation about sourcing and pricing.",
    "He spent a few hours creating a presentation about food security for an upcoming conference, carefully selecting images that honored traditional knowledge.",
    "Kemi received a package of rare seeds from a contact in Ghana and got excited about the potential for a new product line.",
    "One rainy day, he watched documentaries about indigenous farming practices while testing different flavor combinations for energy bars.",
    "Kemi's nephew asked for help with a school science project, and they spent the afternoon extracting natural dyes from hibiscus flowers.",
    "He accidentally left his laptop charger at the office and had to work on his phone, which made reviewing spreadsheets challenging.",
    "Kemi bought new books about food technology and nutritional biochemistry, adding them to his already overflowing bookshelf.",
    "One morning, he had to rush to catch a bus after losing track of time while perfecting a new baobab processing technique.",
    "Kemi had a quiet dinner at home, eating traditional Nigerian soup while responding to emails from international distributors.",
    "He spent time this week responding to messages from young entrepreneurs seeking mentorship, carefully crafting encouraging responses.",
    "Kemi found himself running late to a team meeting after getting absorbed in a conversation with a traditional healer about medicinal plants.",
    "He spent some time updating his company's website with new research findings, ensuring the information was accessible to non-technical readers.",
    "One afternoon, Kemi took a break from work to sit in his small rooftop garden, tending to the moringa and bitter leaf plants he grows.",
    "He accidentally mixed up two similar-looking plant samples and spent an hour re-labeling everything to avoid future confusion.",
    "Kemi dropped by a new African restaurant to research how traditional ingredients were being used in modern culinary applications.",
    "He spent his Saturday morning catching up on calls with farmers in rural communities, discussing crop yields and market demands.",
    "While cleaning his apartment, Kemi found old coding notebooks from university that reminded him of his journey from pure tech to food innovation."
]

occupation = [
    "Kemi successfully launched a line of high-protein snacks made from indigenous African grains, securing distribution in five West African countries.",
    "He organized a workshop for local farmers on sustainable cultivation techniques for high-value indigenous plants like moringa and baobab.",
    "Kemi spent weeks developing a proprietary extraction process that preserves maximum nutrients while extending shelf life for traditional African superfoods.",
    "He attended an agri-tech conference in Nairobi where he networked with other African food entrepreneurs and secured three new partnership deals.",
    "Kemi had to navigate a complex negotiation with government regulators to get approval for his innovative food processing methods.",
    "During a busy quarter, Kemi worked overtime to complete clinical trials demonstrating the health benefits of his flagship moringa-based supplement.",
    "He collaborated with nutritionists at Lagos University to publish research papers validating the nutritional superiority of indigenous African plants.",
    "Kemi conducted a market analysis of the global superfood industry, identifying opportunities for African ingredients in international markets.",
    "He delivered a keynote presentation at a food security summit, advocating for investment in indigenous African food systems and local innovation.",
    "Kemi mentored a cohort of young African entrepreneurs through a startup accelerator focused on agriculture technology.",
    "He hosted a webinar for international investors about the untapped potential of African food technology and traditional nutritional knowledge.",
    "Kemi was tasked with developing a supply chain management system that ensures fair compensation for rural farmers growing indigenous crops.",
    "He spent days in the field working with agricultural scientists to optimize growing conditions for nutrient-dense African vegetables.",
    "Kemi met with the Minister of Agriculture to discuss policy changes that would support local food innovation and reduce import dependency.",
    "He trained his production team on new quality control protocols to ensure AfriFoods Tech products meet international safety standards.",
    "Kemi was invited to speak at a United Nations panel about leveraging traditional knowledge for modern nutrition solutions in developing countries.",
    "He reviewed and approved expansion plans for manufacturing facilities in three additional African countries, focusing on local job creation.",
    "Kemi collaborated with anthropologists and ethnobotanists to document and preserve traditional food preparation methods before they're lost.",
    "He developed a blockchain-based certification system that allows consumers to trace ingredients back to specific farming communities.",
    "After months of research and development, Kemi launched a mobile app that educates users about the nutritional benefits of indigenous African foods."
]

kemi_memories = core + mundane + occupation