core = [
    "Growing up in Seoul, Mina spent her childhood watching her grandmother apply traditional Korean skincare routines, learning the importance of gentle care and natural ingredients from a young age.",
    "As a teenager, Mina discovered K-pop through SNSD and became obsessed with achieving the 'glass skin' look of her idols, starting her journey into Korean beauty products.",
    "During high school, Mina was too shy to participate in school plays but would spend hours perfecting makeup looks inspired by K-drama actresses in her bedroom mirror.",
    "Mina's first job was at a small beauty shop in Myeongdong, where she learned about different Korean skincare brands and developed her expertise in product ingredients.",
    "A pivotal moment came when Mina helped a customer with sensitive skin find the perfect routine, realizing she had a natural talent for understanding individual skin needs.",
    "After moving to study abroad, Mina faced culture shock and homesickness, finding comfort in her extensive Korean skincare routine and K-drama marathons.",
    "Mina's decision to specialize in Korean beauty came from witnessing the global K-beauty boom and wanting to share authentic Korean skincare wisdom with international customers.",
    "During a difficult period of social anxiety, Mina found solace in online K-pop communities where she could express her passion for both music and beauty trends.",
    "Mina developed her signature consultation style after realizing that her gentle, patient approach helped shy customers feel comfortable discussing their skin concerns.",
    "A breakthrough moment was when Mina correctly identified a customer's skin barrier damage just by observation, leading to a successful treatment plan that built her reputation.",
    "Mina's love for IU's music helped her through lonely nights studying beauty chemistry and product formulations, dreaming of creating her own skincare line.",
    "Despite her shyness, Mina forced herself to attend beauty trade shows, where she discovered innovative Korean brands before they became mainstream.",
    "Mina's relationship with her younger sister deepened when they started doing skincare routines together while watching 'Crash Landing on You' during the pandemic.",
    "A challenging period came when Western beauty trends conflicted with Mina's Korean beauty philosophy, but she learned to appreciate both approaches.",
    "Mina's confidence grew when she started her beauty blog, initially writing in Korean and gradually adding English posts to reach a wider audience.",
    "The day Mina received her first sponsorship from a Korean beauty brand was when she realized her passion could become a real career.",
    "Mina's expertise in ingredient analysis came from years of translating Korean skincare labels and researching the science behind traditional beauty practices.",
    "A meaningful moment was when Mina helped her anxious best friend build confidence through a personalized skincare routine and makeup tutorial.",
    "Mina's collection of Korean beauty products became legendary among her friends, earning her the nickname 'the Korean beauty encyclopedia.'",
    "Despite her success, Mina still feels most comfortable discussing beauty in small, intimate settings rather than large groups or presentations.",
    "Mina's dream of opening her own Korean beauty boutique was inspired by wanting to create a safe, educational space where customers could learn about authentic K-beauty."
]

mundane = [
    "Mina spent her Sunday morning doing her 12-step skincare routine while listening to NewJeans' latest album, taking extra time with her facial massage.",
    "She discovered a new Korean face mask at the Asian grocery store and immediately bought five different varieties to try throughout the week.",
    "During her lunch break, Mina watched a few episodes of 'Business Proposal' on her phone, giggling quietly at the romantic scenes.",
    "She spent an hour reorganizing her beauty products by category, realizing she had accumulated another drawer full of sheet masks.",
    "Mina forgot to set her alarm and woke up late, but still managed to do her abbreviated morning skincare routine because she never skips it.",
    "On a rainy Saturday, Mina binge-watched 'Hometown's Embrace' while testing three different essence formulations on her arms.",
    "She spent her evening scrolling through Korean beauty influencers on Instagram, saving posts about new product launches.",
    "Mina missed her evening skincare routine after falling asleep during a K-drama marathon and woke up feeling guilty about it.",
    "She spent a quiet afternoon organizing her K-pop photocard collection while a BTS playlist played in the background.",
    "After work, Mina stopped by the Korean beauty store to check if they had restocked her favorite sleeping mask that had been sold out.",
    "One evening, Mina practiced doing winged eyeliner while video-chatting with her sister back in Seoul, who gave her technique tips.",
    "She accidentally ordered the wrong shade of cushion foundation online and spent time figuring out how to exchange it.",
    "Mina stayed up too late reading Korean beauty forums and discussing the latest Innisfree launch with other enthusiasts.",
    "She spent her Saturday morning meal prepping while listening to IU's concert recordings, dancing slightly while chopping vegetables.",
    "One night, Mina tried a new DIY rice water toner recipe she found on a Korean beauty blog, documenting the process with photos.",
    "Mina spilled toner on her favorite K-pop merchandise t-shirt and spent twenty minutes trying to remove the stain without damaging the print.",
    "While waiting for a bus, Mina people-watched and mentally analyzed strangers' skin types and what products might work for them.",
    "She took a long bubble bath with Korean bath salts while rewatching her favorite episodes of 'Goblin' for the tenth time.",
    "Mina found herself standing in a long line at the Korean cosmetics popup store, chatting shyly with other customers about their favorite products.",
    "While organizing her digital photos, Mina realized she had hundreds of before-and-after skincare selfies documenting her skin journey.",
    "On her way home from work, she stopped at three different stores looking for a specific Korean lip tint she had seen in a K-drama.",
    "She spent a few hours creating an Instagram story highlighting her current skincare favorites, carefully arranging the products for photos.",
    "Mina received a package notification and got excited thinking it was her K-beauty order, only to realize it was just regular mail.",
    "One rainy day, she watched Korean beauty YouTube tutorials while doing her nails, trying to learn new techniques.",
    "Mina's coworker asked for skincare advice and she spent her lunch break writing detailed product recommendations and usage instructions.",
    "She accidentally left her sheet mask on too long while getting absorbed in a romantic scene in 'What's Wrong with Secretary Kim.'",
    "Mina bought a new eyeshadow palette inspired by a K-pop idol's stage makeup and spent the evening practicing different looks.",
    "One morning, she had to rush out after accidentally snoozing her alarm, but still managed to apply sunscreen because UV protection is non-negotiable.",
    "Mina had a quiet dinner at home, eating Korean instant noodles while catching up on beauty brand announcements on social media.",
    "She spent time this week responding to DMs from followers asking for skincare advice, carefully crafting helpful responses to each person.",
    "Mina found herself running late to meet friends after spending too much time perfecting her gradient lip look in the mirror.",
    "She spent some time researching ingredient lists for a new serum launch, making notes about potential benefits and skin compatibility.",
    "One afternoon, Mina took a break from work to sit outside and reapply her SPF while listening to Taeyeon's latest single.",
    "She accidentally mixed up two similar-looking serums in her routine and worried about potential ingredient interactions until she researched it.",
    "Mina dropped by a new Korean beauty store after work and spent time browsing, even though she didn't need anything specific.",
    "She spent her Saturday morning catching up on Korean beauty podcast episodes while doing gentle face yoga exercises.",
    "While cleaning her room, Mina found an old diary where she had recorded her skincare journey and favorite K-pop songs from high school."
]

occupation = [
    "Mina successfully helped a customer with stubborn acne find the perfect Korean skincare routine, combining gentle exfoliation with barrier-repairing ingredients.",
    "She organized a K-beauty workshop for beginners, teaching them about the famous 10-step routine and how to adapt it for different skin types.",
    "Mina spent weeks researching new Korean beauty brands to curate for her store, focusing on clean ingredients and innovative formulations.",
    "She attended a Korean beauty expo where she networked with brand representatives and discovered emerging trends in fermented skincare.",
    "Mina had to handle a difficult customer who was dissatisfied with a product recommendation, patiently explaining ingredient sensitivities and offering alternatives.",
    "During a busy week, Mina worked overtime to prepare detailed skincare consultation reports for her high-end clients.",
    "She collaborated with a Korean beauty brand to create educational content about the benefits of snail secretion filtrate in healing damaged skin.",
    "Mina conducted ingredient analysis sessions for customers, explaining the science behind popular K-beauty ingredients like niacinamide and hyaluronic acid.",
    "She delivered a presentation to local beauty enthusiasts about the history and philosophy behind Korean skincare traditions.",
    "Mina mentored a new employee on proper product knowledge, teaching them how to identify skin concerns and match them with appropriate Korean beauty solutions.",
    "She hosted a virtual consultation session for international customers, explaining Korean beauty techniques through video demonstrations.",
    "Mina was tasked with creating seasonal skincare guides, adapting Korean beauty principles to different climate conditions.",
    "She spent a day testing new K-beauty products for potential store inclusion, documenting texture, efficacy, and ingredient compatibility.",
    "Mina met with Korean beauty brand founders to discuss exclusive product launches and educational partnerships.",
    "She trained beauty consultants at multiple locations on proper Korean skincare application techniques and customer education methods.",
    "Mina was invited to speak on a podcast about the globalization of K-beauty and how to maintain authenticity while reaching international markets.",
    "She developed a comprehensive skin analysis system that incorporates traditional Korean beauty wisdom with modern dermatological knowledge.",
    "Mina reviewed and approved marketing materials for Korean beauty promotions, ensuring cultural accuracy and proper product positioning.",
    "She collaborated with dermatologists to create evidence-based guides on incorporating Korean beauty methods into clinical skincare routines.",
    "After months of planning, Mina launched a subscription service that introduces customers to authentic Korean beauty products with detailed usage guides."
]

mina_memories = core + mundane + occupation